### ISSUE TITLE
White Desktop background bug with Numix Frost and Frost Light themes

### ISSUE THREAD

**Issue by momashi** [Antergos/Numix-Frost#22] opened 2016-01-04 00:41 UTC
![screenshot from 2016-01-03 19-42-20](https://cloud.githubusercontent.com/assets/1645713/12081756/5901c530-b252-11e5-8266-a8e3179b06b9.png)
![screenshot from 2016-01-03 19-42-41](https://cloud.githubusercontent.com/assets/1645713/12081759/60ac292e-b252-11e5-8379-26bd4a897782.png)

I'm using Gnome Shell version of Antergos, fully up to date. I have the desktop icons turned on (this bug doesn't manifest with the icons off).

I'm getting a white background instead of my wallpaper when I have either Numix Frost or Numix Frost Light selected for GTK+. The white background dissapears and my regular wallpaper is seen Gnome Shell overview. If I turn off Nautilus handling of desktop icons, the white background goes away.

If I switch Numix Frost for say Adwaita theme or even an older version of Numix Frost in GTK+, the bug no longer happens. The bug is in GTK+, it is not affected by what theme I choose for gnome shell. I'm guessing there's a line somewhere that deals with the desktop background that may have been omitted in the new version of the GTK branch of the bug.

**Comment by lots0logs** [comment] 2016-01-04 01:09
Duplicate of #14

**Closed by lots0logs** 2016-01-04 01:09 UTC
Labels: duplicate
